IF
	True()
THEN
	RESPONSE #100
		CutSceneId("Korgan")
		MoveViewPoint([724.685],2)
		MoveToPoint([724.685])
		Wait(3)
		ForceSpell(Myself,BERSERKER_RAGE)
		AttackOneRound([NEUTRAL])
		SetGlobal("JZPanic","GLOBAL",1)
		// Wait(2)
		AttackOneRound([NEUTRAL])
		// Wait(2)
		AttackOneRound([NEUTRAL])
		SetGlobal("JZPanic","GLOBAL",2)
		Wait(2)
		ActionOverride("JZJerry",StartDialogueNoSet(Player1))
END
